feat: add missing geography field
terraform-ibm-modules/terraform-ibm-cbr pull request #519
Opened 2024-09-02 14:57 UTC by rajatagarwal-ibm

### Description

Added missing "geography" attribute

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-09-02 14:57 UTC, rajatagarwal-ibm commented
/run pipeline

2024-09-02 15:19 UTC, rajatagarwal-ibm commented
PR failed with the following error - added prefix to the string to avoid it in the future.

```
Error: CreateZoneWithContext failed. A network zone with the same name already exists. Assign each network zone a unique name.
{
    "StatusCode": 409,
    "Headers": {
        "Akamai-Grn": ["0.9dce4917.1725289640.10814556"],
        "Cache-Control": ["no-cache,no-store"],
        "Content-Length": ["317"],
        "Content-Type": ["application/json; charset=utf-8"],
        "Date": ["Mon, 02 Sep 2024 15:07:20 GMT"],
        "Expires": ["Thursday, 1 January 1970 00:00:00 GMT"],
        "Pragma": ["no-cache"],
        "Strict-Transport-Security": ["max-age=31536000; includeSubDomains"],
        "Transaction-Id": ["425b383c-60ce-4787-b208-4b9f8855f3b6"],
        "X-Content-Type-Options": ["nosniff"],
        "X-Correlation-Id": ["425b383c-60ce-4787-b208-4b9f8855f3b6"],
        "X-Proxy-Upstream-Service-Time": ["475"],
        "X-Ratelimit-Limit": ["10"],
        "X-Ratelimit-Remaining": ["9"],
        "X-Ratelimit-Reset": ["1725289641"]
    },
    "Result": {
        "errors": [
            {
                "code": "zone_already_exists_in_store",
                "message": "A network zone with the same name already exists. Assign each network zone a unique name.",
                "target": {
                    "name": "name",
                    "type": "field",
                    "value": "codeengine-zone-example-of-customized-zone-name"
                }
            }
        ],
        "status_code": 409,
        "trace": "425b383c-60ce-4787-b208-4b9f8855f3b6"
    },
    "RawResult": null
}

Error: CreateZoneWithContext failed. A network zone with the same name already exists. Assign each network zone a unique name.
{
    "StatusCode": 409,
    "Headers": {
        "Akamai-Grn": ["0.076bdc17.1725289640.3dcf8d31"],
        "Cache-Control": ["no-cache,no-store"],
        "Content-Length": ["310"],
        "Content-Type": ["application/json; charset=utf-8"],
        "Date": ["Mon, 02 Sep 2024 15:07:20 GMT"],
        "Expires": ["Thursday, 1 January 1970 00:00:00 GMT"],
        "Pragma": ["no-cache"],
        "Strict-Transport-Security": ["max-age=31536000; includeSubDomains"],
        "Transaction-Id": ["6b2f528e-36b0-4ddf-8805-359ae7d94d40"],
        "X-Content-Type-Options": ["nosniff"],
        "X-Correlation-Id": ["6b2f528e-36b0-4ddf-8805-359ae7d94d40"],
        "X-Proxy-Upstream-Service-Time": ["128"],
        "X-Ratelimit-Limit": ["10"],
        "X-Ratelimit-Remaining": ["0"],
        "X-Ratelimit-Reset": ["1725289641"]
    },
    "Result": {
        "errors": [
            {
                "code": "zone_already_exists_in_store",
                "message": "A network zone with the same name already exists. Assign each network zone a unique name.",
                "target": {
                    "name": "name",
                    "type": "field",
                    "value": "COS-zone-example-of-customized-zone-name"
                }
            }
        ],
        "status_code": 409,
        "trace": "6b2f528e-36b0-4ddf-8805-359ae7d94d40"
    },
    "RawResult": null
}

```

2024-09-02 15:19 UTC, rajatagarwal-ibm commented
/run pipeline

2024-09-03 07:02 UTC, Ak-sky requested changes

2024-09-03 07:02 UTC, Ak-sky commented on modules/fscloud/variables.tf
I think we also need a validation for a service if it supports `geography` like we have a validation for `region`.

2024-09-03 09:07 UTC, rajatagarwal-ibm commented
@Ak-sky I don't understand, custom names could have prefixes as well, right? I need to create that because it failed due to the naming conflict, see the error in the comment above.

2024-09-03 09:39 UTC, rajatagarwal-ibm commented
@Ak-sky, I think we might need to remove the `region` attribute. I have added this topic to discuss with the wider audience.

2024-09-04 09:16 UTC, Ak-sky commented on modules/fscloud/variables.tf
> +    error_message = "Both `region` and `geography` cannot be set simultaneously for the target service."
Geography is only applicable for `container-registry` and not for any other service. So validation has to be set specifically for `container-registry`.

```
Tgt. Services REGION SUPPORTED: 23
["cloud-object-storage", "codeengine", "container-registry", "containers-kubernetes", "databases-for-elasticsearch", "databases-for-enterprisedb", "databases-for-etcd", "databases-for-mongodb", "databases-for-mysql", "databases-for-postgresql", "databases-for-redis", "event-notifications", "hs-crypto", "iam-identity", "is", "logdna", "logdnaat", "messagehub", "messages-for-rabbitmq", "mqcloud", "secrets-manager", "sysdig-monitor", "sysdig-secure"]

Tgt. Services REGION NOT SUPPORTED: 13
["IAM", "apprapp", "compliance", "context-based-restrictions", "directlink", "dns-svcs", "globalcatalog-collection", "iam-access-management", "iam-groups", "kms", "schematics", "transit", "user-management"]

Tgt. Services GEOGRAPHY SUPPORTED: 1
["container-registry"]
```

2024-09-04 13:08 UTC, rajatagarwal-ibm commented
/run pipeline

2024-09-05 12:56 UTC, rajatagarwal-ibm commented
/run pipeline

2024-09-05 13:39 UTC, vburckhardt commented
/run pipeline

2024-09-05 13:39 UTC, vburckhardt commented on examples/fscloud/main.tf
> +    "container-registry" : {
I think we should just document this in the example README.md as well

2024-09-05 13:51 UTC, rajatagarwal-ibm commented
/run pipeline

2024-09-09 08:52 UTC, rajatagarwal-ibm commented
/run pipeline

2024-09-09 18:27 UTC, Ak-sky approved these changes

2024-09-10 08:49 UTC, merged

2024-09-10 08:50 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 1.25.0 :tada:

The release is available on [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-cbr/releases/tag/v1.25.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: